# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!


target 'HeartRate' do
  pod 'Socket.IO-Client-Swift', '~> 4.1.6'
end